

import HeaderPage from './HeaderPage/page'
import HomePage from './HomePage/page'
import Footer from'./FooterPage/page'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        {children}
        <HomePage/>
        <HeaderPage/>
        <Footer></Footer>
      </body>
    </html>
  )
}
